---
title: "andrew_visualizations"
author: "andrew-s-thompson"
date: "2024-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

get(load("DATA_FILES/ALL_COUNTY_DATA.RData"))

library(tidyverse)
```

## R Markdown

This displays number of observations in each sector.

```{r}
ggplot(combined, aes(x = sector_desc)) + 
  geom_bar()
```

```{r}
combined %>% 
  filter(sector_desc == "ECONOMICS", state_name == "INDIANA") %>%
  group_by(commodity_desc, year) %>%  # Group by both commodity and year
  summarize(total_value = sum(Value, na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = total_value, color = commodity_desc, group = commodity_desc)) +
  geom_line(size = 1) +  # Line size for visibility
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Commodity Value Over Time in Indiana (Economics Sector)", 
       x = "Year", 
       y = "Total Value")
```
```{r}
combined %>% 
group_by(state_name, Value, year) %>%
  summarize(value_sum = sum(Value, na.rm=TRUE)) %>% 
ggplot(aes(x = year, y = value_sum, color = state_name, group = state_name)) + 
  geom_line()

combined %>% 
   filter(!str_detect(commodity_desc, "(?i)total")) %>% 
group_by(state_name, year) %>%  # Group by both commodity and year
  summarize(value_sum = sum(Value, na.rm=TRUE)) %>% 
ggplot(aes(x = year, y = value_sum, color = state_name, group = state_name)) + 
  geom_line() +  # Line size for visibility
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Commodity Value Over Time by State", 
       x = "Year", 
       y = "Total Commodity Values")

```


```{r}

list_state_names = c("INDIANA", "ILLINOIS", "MICHIGAN", "MISSOURI", "KENTUCKY", "OHIO")

combined %>% 
  filter(state_name == "INDIANA") %>% 
group_by(county_name, Value, year) %>%
  summarize(value_sum = sum(Value, na.rm=TRUE)) %>% 
ggplot(aes(x = year, y = value_sum, color = county_name, group = county_name)) + 
  geom_bar()

combined %>% 
  filter(!str_detect(commodity_desc, "(?i)total"), state_name == "INDIANA") %>% 
group_by(county_name, year) %>%  # Group by both commodity and year
  summarize(value_sum = sum(Value, na.rm=TRUE)) %>% 
ggplot(aes(x = year, y = value_sum, color = county_name, group = county_name)) + 
  geom_line() +  # Line size for visibility
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Commodity Value Over Time by State", 
       x = "Year", 
       y = "Total Commodity Values")

```